import { Inter, Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
import Script from 'next/script';
import type { Metadata } from "next";

const inter = Inter({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-inter',
});

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-plus-jakarta',
});

export const metadata: Metadata = {
  title: "24/7 Support  |  Contact Support",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} ${plusJakartaSans.variable}`}>
      <head>
        <Script
         async src="https://www.googletagmanager.com/gtag/js?id=AW-16526856628"
        />
        <Script id="google-ads-tag" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-16526856628');
          `}
        </Script>
      </head>
      <body>
        {children}
        </body>
    </html>
  );
}